spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 属性值为空时不做序列化
    default-property-inclusion: non_null

project:
  name: elementui-api
  version: 0.0.1
  author:
    name: lij

