###############################################################################
## dev 开发环境
###############################################################################

## 服务配置
server:
  port: 8088

## 数据库设置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_jpa?useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      validation-query: SELECT 1
      max-pool-prepared-statement-per-connection-size: 20
      filters: log4j

  jpa:
    database: MYSQL
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #允许脱离事务的懒加载
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
        naming:
          #驼峰转下划线
          physical-strategy: org.hibernate.boot.model.naming.SpringPhysicalNamingStrategy

##日志配置路径
logging:
  config: classpath:log4j2-dev.xml

## swagger配置
swagger:
  enable: false

##webservices
#webservices:
#  config:
#    - name: myWebService
#      wsdlUrl: http://localhost:8088/ws/user?wsdl
#      connectionTimeout: 30000
#      receiveTimeout: 15000
#    - name: ip-search
#      wsdlUrl: http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl