server:
  port: 8088
  context-path: /
  tomcat:
    uri-encoding: UTF-8

debug: false

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_db?useUnicode=true&characterEncoding=utf-8
      username: test
      password: 123456
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000